### PR TITLE
Updated home and footer page

### PR DESCRIPTION
**Pull request by ShravaniPathak**

### CODE REVIEW

**Comment by rudrathegreat** [comment]
who asked for the changes?

**Comment by ShravaniPathak** [comment]
@rudrathegreat I've made the changes according to the document provided by Ronit

**Comment by rudrathegreat** [comment]
wait which document?

**Comment by rudrathegreat** [comment]
the reason why i'm asking is because a lot of the changes are removing stuff that I spent multiple days non-stop working on

**Comment by ShravaniPathak** [comment]
@rudrathegreat Please have a talk with Rohit regarding the changes

**Pull request merged**
